feat: parse a template yaml into an object
screwdriver-cd/template-validator pull request #3
Opened 2017-03-01 01:22 UTC by FenrirUnbound

## Context

The [`screwdriver-config-parser`](https://github.com/screwdriver-cd/config-parser) is utilized to validate a `screwdriver.yaml` that it meets structural and functional specifications. We want to provide and use a similar module, but for `screwdriver-template.yaml`. 

Since the `screwdriver-config-parser` does very well by focusing on the `screwdriver.yaml`, we wanted to have a separate module that's single responsibility is on the template file. 

## Objective

This PR aims to allow the caller to provide a `screwdriver-template.yaml` (in the form of a string) and receive the JSON representation of it. This function only parses the given template and does *not* validate it.

## Notes

Relies on screwdriver-cd/data-schema#109 to include the validation.

2017-03-01 19:54 UTC, petey requested changes

2017-03-01 19:54 UTC, petey commented on test/index.test.js
> +    return new Promise((resolve, reject) => {
There are promise-based wrappers for `fs` (https://www.npmjs.com/package/mz). Or you could use the `Sync` version, `fs.readFileSync`, for tests to make this cleaner.

2017-03-01 19:54 UTC, petey commented on test/index.test.js
> +        const validFullTemplate = readConfig('valid_full_template.yaml');
Why not make this a constant for the entire file?

2017-03-01 19:54 UTC, petey commented on test/index.test.js
> +        return validFullTemplate
Tests are documentation for code. Better to explicitly show how this code is called.

```
return main(yamlStr).then(...);
```

2017-03-02 01:47 UTC, tkyi requested changes
Could you add a sample template in the README?

2017-03-02 06:26 UTC, d2lam commented on README.md
> +
Add `Usage` on how to use this package?

2017-03-02 18:57 UTC, FenrirUnbound commented on README.md
> +
Expanded the `usage` section to include a sample script

2017-03-02 20:52 UTC, tkyi approved these changes
👍 LGTM
![](http://media1.giphy.com/media/LHppJaeqcocmY/200w.gif)

2017-03-03 01:30 UTC, d2lam approved these changes

2017-03-03 18:33 UTC, petey approved these changes

2017-03-03 18:33 UTC, merged